"""Blog post data models for the blog generation pipeline."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Self


@dataclass
class BlogPostData:
    """Structured blog post generated by the BlogPostGenerationPromptAgent.

    Stores the full blog content along with metadata for S3 and database storage.
    """

    title: str = ""
    content: str = ""
    slug: str = ""
    tags: list[str] = field(default_factory=list)
    meta_description: str = ""
    tone: str = ""
    topic: str = ""
    word_count: int = 0
    generated_at: datetime = field(default_factory=datetime.now)
    s3_key: str | None = None
    job_id: str | None = None

    def to_json(self) -> dict[str, Any]:
        return {
            "title": self.title,
            "content": self.content,
            "slug": self.slug,
            "tags": self.tags,
            "meta_description": self.meta_description,
            "tone": self.tone,
            "topic": self.topic,
            "word_count": self.word_count,
            "generated_at": self.generated_at.isoformat(),
            "s3_key": self.s3_key,
            "job_id": self.job_id,
        }

    @classmethod
    def to_cls(cls, data: dict[str, Any]) -> Self:
        return cls(
            title=data.get("title", ""),
            content=data.get("content", ""),
            slug=data.get("slug", ""),
            tags=data.get("tags", []),
            meta_description=data.get("meta_description", ""),
            tone=data.get("tone", ""),
            topic=data.get("topic", ""),
            word_count=data.get("word_count", 0),
            generated_at=(
                datetime.fromisoformat(data["generated_at"])
                if "generated_at" in data
                else datetime.now()
            ),
            s3_key=data.get("s3_key"),
            job_id=data.get("job_id"),
        )
